import type { Metadata } from "next";
import "./globals.css";
import "react-loading-skeleton/dist/skeleton.css";

import Footer from "@/components/common/layout/Footer";
import Navigation from "@/components/common/layout/Navigation";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body>
        <main className='max-w-[600px] mx-auto'>
          {children}
          <Footer />
          <Navigation />
        </main>
      </body>
    </html>
  );
}
